name: My First workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome to github action
              run: echo "My first github action job executed on $date"

            - name: List files
              run: ls

            - name: Read file
              run: cat README.md


