name: Generate ASCSII

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
    test_job_2:
        runs-on: ubuntu-latest
        steps:
            - name: List repo files
              run: |
                   ls -ltra
                   chmod +x ascii-script.sh

    deploy_job_3:
        runs-on: ubuntu-latest
        steps:
            - name: Executing shell script & checking the content
              run: ./ascii-script.sh