name: Generate ASCSII

on: push

jobs:
    download_code_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Upload base Code
              uses: actions/upload-artifact@v4
              with:
                name: base-checkout-code
                path: ./
            
    configure_job_2:
        needs: download_code_job_1
        runs-on: ubuntu-latest
        steps:
            - name: Download base Code
              uses: actions/download-artifact@v4
              with:
                name: base-checkout-code


            - name: List repo files
              run: |
                   ls -ltra ./
                   echo "Changing Permission of a script" 
                   chmod +x ./ascii-script.sh
                   ls -ltra ./ascii-script.sh

    deploy_job_3:
        needs: [ download_code_job_1, configure_job_2]
        runs-on: ubuntu-latest
        steps:
            - name: Download base Code
              uses: actions/download-artifact@v4
              with:
                name: base-checkout-code

            - name: Executing shell script & checking the content
              run: |
                    ls ./
                    pwd
                    sh ./ascii-script.sh
            
            - name: Upload base Code
              uses: actions/upload-artifact@v4
              with:
                name: base-checkout-code
                path: ./

    test_job_4:
        needs: [ download_code_job_1, configure_job_2, deploy_job_3]
        runs-on: ubuntu-latest
        steps:
            - name: Download base Code
              uses: actions/download-artifact@v4
              with:
                name: base-checkout-code

            - name: Check file context
              run: |
                    ls ./
                    cat ./dragon.txt
