name: Generate ASCSII

on: push

jobs:
    ascsii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: List repo files
              run: |
                    ls -ltra
                    chmod +x ascii-script.sh

            - name: Executing shell script
              run: ./ascii-script.sh